USE app;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS famous_americans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(64) NOT NULL,
  LastName VARCHAR(64) NOT NULL,
  StateOfOrigin VARCHAR(64) NOT NULL,
  StateEmoji VARCHAR(16) NOT NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO famous_americans (FirstName, LastName, StateOfOrigin, StateEmoji) VALUES
  ('George', 'Washington', 'Virginia', '🏛️'),
  ('Abraham', 'Lincoln', 'Illinois', '🌬️'),
  ('Thomas', 'Jefferson', 'Virginia', '🏛️'),
  ('Benjamin', 'Franklin', 'Pennsylvania', '🔔'),
  ('Alexander', 'Hamilton', 'New York', '🗽'),
  ('Mark', 'Twain', 'Missouri', '🎺'),
  ('Ernest', 'Hemingway', 'Illinois', '🌬️'),
  ('Emily', 'Dickinson', 'Massachusetts', '🦞'),
  ('Walt', 'Whitman', 'New York', '🗽'),
  ('Edgar Allan', 'Poe', 'Massachusetts', '🦞'),
  ('Harriet', 'Tubman', 'Maryland', '🦀'),
  ('Frederick', 'Douglass', 'Maryland', '🦀'),
  ('Martin Luther', 'King Jr.', 'Georgia', '🍑'),
  ('Rosa', 'Parks', 'Alabama', '🏈'),
  ('Susan B.', 'Anthony', 'Massachusetts', '🦞'),
  ('Thomas', 'Edison', 'Ohio', '🌰'),
  ('Nikola', 'Tesla', 'New York', '🗽'),
  ('Henry', 'Ford', 'Michigan', '🚗'),
  ('Wright', 'Brothers', 'Ohio', '🌰'),
  ('Amelia', 'Earhart', 'Kansas', '🌻'),
  ('Neil', 'Armstrong', 'Ohio', '🌰'),
  ('Buzz', 'Aldrin', 'New Jersey', '🏖️'),
  ('Sally', 'Ride', 'California', '🌴'),
  ('John', 'Glenn', 'Ohio', '🌰'),
  ('Steve', 'Jobs', 'California', '🌴'),
  ('Bill', 'Gates', 'Washington', '🌲'),
  ('Elon', 'Musk', 'Texas', '🤠'),
  ('Jeff', 'Bezos', 'New Mexico', '🌵'),
  ('Mark', 'Zuckerberg', 'New York', '🗽'),
  ('Oprah', 'Winfrey', 'Mississippi', '🎷'),
  ('Walt', 'Disney', 'Illinois', '🌬️'),
  ('Elvis', 'Presley', 'Mississippi', '🎷'),
  ('Louis', 'Armstrong', 'Louisiana', '⚜️'),
  ('Miles', 'Davis', 'Illinois', '🌬️'),
  ('Duke', 'Ellington', 'Washington D.C.', '⭐'),
  ('Ella', 'Fitzgerald', 'Virginia', '🏛️'),
  ('Jimi', 'Hendrix', 'Washington', '🌲'),
  ('Bob', 'Dylan', 'Minnesota', '❄️'),
  ('Johnny', 'Cash', 'Arkansas', '💎'),
  ('Dolly', 'Parton', 'Tennessee', '🎸'),
  ('Aretha', 'Franklin', 'Tennessee', '🎸'),
  ('Ray', 'Charles', 'Georgia', '🍑'),
  ('Stevie', 'Wonder', 'Michigan', '🚗'),
  ('Michael', 'Jackson', 'Indiana', '🏎️'),
  ('Prince', 'Rogers Nelson', 'Minnesota', '❄️'),
  ('Whitney', 'Houston', 'New Jersey', '🏖️'),
  ('Frank', 'Sinatra', 'New Jersey', '🏖️'),
  ('Marilyn', 'Monroe', 'California', '🌴'),
  ('James', 'Dean', 'Indiana', '🏎️'),
  ('Humphrey', 'Bogart', 'New York', '🗽'),
  ('Katharine', 'Hepburn', 'Connecticut', '🍂'),
  ('Audrey', 'Hepburn', 'Illinois', '🌬️'),
  ('Clint', 'Eastwood', 'California', '🌴'),
  ('Robert', 'De Niro', 'New York', '🗽'),
  ('Meryl', 'Streep', 'New Jersey', '🏖️'),
  ('Morgan', 'Freeman', 'Tennessee', '🎸'),
  ('Denzel', 'Washington', 'New York', '🗽'),
  ('Tom', 'Hanks', 'California', '🌴'),
  ('Robin', 'Williams', 'Illinois', '🌬️'),
  ('Muhammad', 'Ali', 'Kentucky', '🐴'),
  ('Michael', 'Jordan', 'New York', '🗽'),
  ('Babe', 'Ruth', 'Maryland', '🦀'),
  ('Jackie', 'Robinson', 'Georgia', '🍑'),
  ('Jesse', 'Owens', 'Alabama', '🏈'),
  ('Billie Jean', 'King', 'California', '🌴'),
  ('Serena', 'Williams', 'Michigan', '🚗'),
  ('LeBron', 'James', 'Ohio', '🌰'),
  ('Tom', 'Brady', 'California', '🌴'),
  ('Simone', 'Biles', 'Texas', '🤠'),
  ('John F.', 'Kennedy', 'Massachusetts', '🦞'),
  ('Theodore', 'Roosevelt', 'New York', '🗽'),
  ('Franklin D.', 'Roosevelt', 'New York', '🗽'),
  ('Dwight D.', 'Eisenhower', 'Texas', '🤠'),
  ('Ronald', 'Reagan', 'Illinois', '🌬️'),
  ('Barack', 'Obama', 'Hawaii', '🌺'),
  ('Ulysses S.', 'Grant', 'Ohio', '🌰'),
  ('Andrew', 'Jackson', 'South Carolina', '🌙'),
  ('James', 'Madison', 'Virginia', '🏛️'),
  ('John', 'Adams', 'Massachusetts', '🦞'),
  ('Herman', 'Melville', 'New York', '🗽'),
  ('F. Scott', 'Fitzgerald', 'Minnesota', '❄️'),
  ('John', 'Steinbeck', 'California', '🌴'),
  ('Harper', 'Lee', 'Alabama', '🏈'),
  ('Toni', 'Morrison', 'Ohio', '🌰'),
  ('Maya', 'Angelou', 'Missouri', '🎺'),
  ('Langston', 'Hughes', 'Missouri', '🎺'),
  ('Robert', 'Frost', 'California', '🌴'),
  ('Carl', 'Sagan', 'New York', '🗽'),
  ('Jonas', 'Salk', 'New York', '🗽'),
  ('Grace', 'Hopper', 'New York', '🗽'),
  ('Katherine', 'Johnson', 'West Virginia', '⛰️'),
  ('Robert', 'Oppenheimer', 'New York', '🗽'),
  ('Richard', 'Feynman', 'New York', '🗽'),
  ('Rachel', 'Carson', 'Pennsylvania', '🔔'),
  ('Georgia', 'O''Keeffe', 'Wisconsin', '🧀'),
  ('Andy', 'Warhol', 'Pennsylvania', '🔔'),
  ('Jackson', 'Pollock', 'Wyoming', '🦬'),
  ('Norman', 'Rockwell', 'New York', '🗽'),
  ('Ansel', 'Adams', 'California', '🌴');
